### PR TITLE
Some additional improvements; please see commit messages

### PR DESCRIPTION
**Pull request by ADTC**
Please see the individual commits for more details. Thank you. [You can see the preview here.](https://github.com/ADTC/nlp-resume-parser)

Note: I decided against adding `python-dotenv` package as a simple parser would be enough for the `.env` file in our use case.

Regarding tiktoken, see: https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

### CODE REVIEW

**Comment by hxu296** [comment]
Hey, thank you for using tiktoken for exact token counting rather than the previous raw estimate! The .env suppport also looks good. One small thing: I think it's a good idea for `parse_env_file` to look into the environment variables first, and read from .env if `OPENAI_API_KEY` is not set in the environment. This way, we can still overwrite OPENAI_API_KEY on the fly for tests, and .env remains a prod option. What do you think?

**Comment by ADTC** [comment]
I'll add it here.

**Comment by ADTC** [comment]
@hxu296 I've updated as requested, via a force push to change the commits. [Please take a look.](https://github.com/hxu296/nlp-resume-parser/compare/df754ad6146267d3839c84934e3208b1dbf1588f..3b8208f5b4614bdc065aba71835b95cf1380fc3d)

The changes ensure it still works if there's no `.env` file.

**Review by hxu296 — APPROVED** [review]
That's very clean, thank you for your contribution 🎉

**Pull request merged**
